name: hspec-expectations
version: 0.7.2
synopsis: Catchy combinators for HUnit
description: "Catchy combinators for HUnit: <https://github.com/hspec/hspec-expectations#readme>"
license: MIT
copyright: (c) 2011-2015 Simon Hengel
author: Simon Hengel <sol@typeful.net>
maintainer: Simon Hengel <sol@typeful.net>
category: Testing
tested-with: GHC==7.8.4, GHC==7.10.2

github: hspec/hspec-expectations

ghc-options: -Wall

dependencies:
  - base == 4.*
  - HUnit

library:
  source-dirs: src
  exposed-modules:
    - Test.Hspec.Expectations
    - Test.Hspec.Expectations.Contrib

tests:
  spec:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec ==2.*
