name: hspec-expectations
version: 0.7.2
synopsis: Catchy combinators for HUnit
description: "Catchy combinators for HUnit: <https://github.com/hspec/hspec-expectations#readme>"
license: MIT
copyright: (c) 2011-2015 Simon Hengel
author: Simon Hengel <sol@typeful.net>
maintainer: Simon Hengel <sol@typeful.net>
category: Testing

github: hspec/hspec-expectations

ghc-options: -Wall

dependencies:
  - base == 4.*
  - HUnit
  - pretty-show >= 1.6

library:
  source-dirs: src
  exposed-modules:
    - Test.Hspec.Expectations
    - Test.Hspec.Expectations.Contrib
