name: hspec-expectations
version: 0.8.2
synopsis: Catchy combinators for HUnit
description: "Catchy combinators for HUnit: <https://github.com/hspec/hspec-expectations#readme>"
license: MIT
copyright: (c) 2011-2015 Simon Hengel
author: Simon Hengel <sol@typeful.net>
maintainer: Simon Hengel <sol@typeful.net>
category: Testing

github: hspec/hspec-expectations

ghc-options: -Wall

dependencies:
  - base == 4.*
  - call-stack

library:
  source-dirs: src
  dependencies:
    - HUnit
  exposed-modules:
    - Test.Hspec.Expectations
    - Test.Hspec.Expectations.Contrib

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - nanospec
      - HUnit >= 1.5.0.0
      - containers
