name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-16.04 # https://launchpad.net/~hvr/+archive/ubuntu/ghc?field.series_filter=xenial
        ghc:
          - '7.4.2'
          - '7.6.3'
          - '7.8.4'
          - '7.10'
          - '8.0'
          - '8.2'
          - '8.4'
          - '8.6'
          - '8.8'
          - '8.10'
        include:
          - os: macos-latest
            ghc: latest
          - os: windows-latest
            ghc: latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - uses: sol/run-haskell-tests@v1

  success:
    needs: build
    runs-on: ubuntu-latest
    if: always() # this is required as GitHub considers "skipped" jobs as "passed" when checking branch protection rules

    steps:
      - run: false
        if: needs.build.result != 'success'
